version: '3'
services:
  web:
    build: .
    ports:
      - "55000:5000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: