"""empty message

Revision ID: 64511aea48ff
Revises: 51af6ac58c9d
Create Date: 2024-05-10 23:00:38.608680

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64511aea48ff"
down_revision = "51af6ac58c9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
